---

- include: install.deb.yml
  when: ansible_os_family == 'Debian'

- include: install.yum.yml
  when: ansible_os_family == 'RedHat'

- include: configure.yml

- name: Ensure Postfix is started
  action: command /usr/sbin/postfix start
